export const BUTCHER_VOCABULARY = [
  {
    label: 'saudacao',
    title: 'Olá / bom dia',
    text: 'Olá! Bom dia.',
    category: 'Atendimento',
    examples: ['Oi', 'Olá', 'Bom dia', 'Boa tarde', 'Boa noite'],
  },
  {
    label: 'bom-dia',
    title: 'Bom dia',
    text: 'Bom dia! Como posso ajudar?',
    category: 'Atendimento',
    examples: ['Bom dia'],
  },
  {
    label: 'boa-tarde',
    title: 'Boa tarde',
    text: 'Boa tarde! Como posso ajudar?',
    category: 'Atendimento',
    examples: ['Boa tarde'],
  },
  {
    label: 'boa-noite',
    title: 'Boa noite',
    text: 'Boa noite! Como posso ajudar?',
    category: 'Atendimento',
    examples: ['Boa noite'],
  },
  {
    label: 'quero-comprar',
    title: 'Quero comprar',
    text: 'Quero comprar carne.',
    category: 'Atendimento',
    examples: ['Quero comprar carne', 'Vou fazer um pedido'],
  },
  {
    label: 'carne-bovina',
    title: 'Carne bovina',
    text: 'Quero carne bovina.',
    category: 'Produto',
    examples: ['Carne de boi', 'Carne bovina'],
  },
  {
    label: 'carne-suina',
    title: 'Carne suína',
    text: 'Quero carne suína.',
    category: 'Produto',
    examples: ['Carne de porco', 'Carne suína'],
  },
  {
    label: 'frango',
    title: 'Frango',
    text: 'Quero frango.',
    category: 'Produto',
    examples: ['Frango', 'Carne de frango'],
  },
  {
    label: 'linguica',
    title: 'Linguiça',
    text: 'Quero linguiça.',
    category: 'Produto',
    examples: ['Linguiça', 'Linguiça toscana'],
  },
  {
    label: 'carne-moida',
    title: 'Carne moída',
    text: 'Quero carne moída.',
    category: 'Produto',
    examples: ['Carne moída', 'Moer a carne'],
  },
  {
    label: 'picanha',
    title: 'Picanha',
    text: 'Quero picanha.',
    category: 'Corte bovino',
    examples: ['Picanha', 'Corte de picanha'],
  },
  {
    label: 'alcatra',
    title: 'Alcatra',
    text: 'Quero alcatra.',
    category: 'Corte bovino',
    examples: ['Alcatra'],
  },
  {
    label: 'contra-file',
    title: 'Contra-filé',
    text: 'Quero contra-filé.',
    category: 'Corte bovino',
    examples: ['Contra-filé', 'Bife de contra-filé'],
  },
  {
    label: 'patinho',
    title: 'Patinho',
    text: 'Quero patinho.',
    category: 'Corte bovino',
    examples: ['Patinho'],
  },
  {
    label: 'acem',
    title: 'Acém',
    text: 'Quero acém.',
    category: 'Corte bovino',
    examples: ['Acém'],
  },
  {
    label: 'costela',
    title: 'Costela',
    text: 'Quero costela.',
    category: 'Corte',
    examples: ['Costela bovina', 'Costela suína'],
  },
  {
    label: 'bife',
    title: 'Cortar em bifes',
    text: 'Por favor, corte em bifes.',
    category: 'Preparo',
    examples: ['Cortar em bifes', 'Quero bifes'],
  },
  {
    label: 'cubos',
    title: 'Cortar em cubos',
    text: 'Por favor, corte em cubos.',
    category: 'Preparo',
    examples: ['Cortar em cubos', 'Carne em cubos'],
  },
  {
    label: 'moer',
    title: 'Moer a carne',
    text: 'Por favor, moa a carne.',
    category: 'Preparo',
    examples: ['Moer a carne', 'Pode moer?'],
  },
  {
    label: 'quantidade',
    title: 'Quantidade',
    text: 'Quero esta quantidade, por favor.',
    category: 'Pedido',
    examples: ['Quanto?', 'Essa quantidade', 'Mais um pouco'],
  },
  {
    label: 'um-quilo',
    title: 'Um quilo',
    text: 'Quero um quilo.',
    category: 'Pedido',
    examples: ['Um quilo', 'Um kg'],
  },
  {
    label: 'meio-quilo',
    title: 'Meio quilo',
    text: 'Quero meio quilo.',
    category: 'Pedido',
    examples: ['Meio quilo', 'Quinhentas gramas'],
  },
  {
    label: 'numero-um',
    title: 'Um',
    text: 'Um quilo, por favor.',
    category: 'Pedido',
    examples: ['Um', 'Número um'],
  },
  {
    label: 'numero-dois',
    title: 'Dois',
    text: 'Dois quilos, por favor.',
    category: 'Pedido',
    examples: ['Dois', 'Número dois'],
  },
  {
    label: 'numero-tres',
    title: 'Três',
    text: 'Três quilos, por favor.',
    category: 'Pedido',
    examples: ['Três', 'Número três'],
  },
  {
    label: 'numero-quatro',
    title: 'Quatro',
    text: 'Quatro quilos, por favor.',
    category: 'Pedido',
    examples: ['Quatro', 'Número quatro'],
  },
  {
    label: 'numero-cinco',
    title: 'Cinco',
    text: 'Cinco quilos, por favor.',
    category: 'Pedido',
    examples: ['Cinco', 'Número cinco'],
  },
  {
    label: 'preco',
    title: 'Preço',
    text: 'Qual é o preço?',
    category: 'Pedido',
    examples: ['Quanto custa?', 'Qual o preço?'],
  },
  {
    label: 'pagamento-pix',
    title: 'Pagamento por Pix',
    text: 'Vou pagar por Pix.',
    category: 'Pagamento',
    examples: ['Pix', 'Pagar por Pix'],
  },
  {
    label: 'pagamento-cartao',
    title: 'Pagamento no cartão',
    text: 'Vou pagar no cartão.',
    category: 'Pagamento',
    examples: ['Cartão', 'Pagar no cartão'],
  },
  {
    label: 'entrega',
    title: 'Entrega',
    text: 'Vocês fazem entrega?',
    category: 'Serviço',
    examples: ['Tem entrega?', 'Entregar em casa'],
  },
  {
    label: 'horario',
    title: 'Horário de funcionamento',
    text: 'Qual é o horário de funcionamento?',
    category: 'Serviço',
    examples: ['Que horas abre?', 'Que horas fecha?'],
  },
  {
    label: 'fila',
    title: 'Fila / atendimento',
    text: 'Onde é a fila?',
    category: 'Atendimento',
    examples: ['Onde fica a fila?', 'Minha vez'],
  },
  {
    label: 'obrigado',
    title: 'Obrigado',
    text: 'Obrigado.',
    category: 'Atendimento',
    examples: ['Obrigado', 'Muito obrigado'],
  },
  {
    label: 'nao-entendi',
    title: 'Não entendi',
    text: 'Não entendi. Pode repetir?',
    category: 'Atendimento',
    examples: ['Não entendi', 'Pode repetir?'],
  },
]

const VLIBRASIL_CLASS_ALIASES = {
  saudacao: ['Oi'],
  'bom-dia': ['Bom', 'Dia'],
  'boa-tarde': ['Tarde'],
  'boa-noite': ['Noite'],
  'quero-comprar': ['Comprar'],
  'carne-bovina': ['Carne', 'Boi'],
  'carne-suina': ['Porco'],
  frango: ['Frango', 'Galinha'],
  linguica: ['Linguiça', 'Linguiça toscana'],
  'carne-moida': ['Carne moída', 'Moer'],
  picanha: ['Picanha'],
  alcatra: ['Alcatra'],
  'contra-file': ['Contra-filé', 'Contra file'],
  patinho: ['Patinho'],
  acem: ['Acém'],
  costela: ['Costela'],
  bife: ['Bife'],
  cubos: ['Cubo', 'Cubos'],
  moer: ['Moer'],
  quantidade: ['Quantidade'],
  'um-quilo': ['Quilo'],
  'meio-quilo': ['Meio quilo', 'Quinhentas gramas'],
  'numero-um': ['Um'],
  'numero-dois': ['Dois'],
  'numero-tres': ['Três'],
  'numero-quatro': ['Quatro'],
  'numero-cinco': ['Cinco'],
  preco: ['Preço'],
  'pagamento-pix': ['Pix'],
  'pagamento-cartao': ['Cartão', 'Cartão de Crédito'],
  entrega: ['Entrega'],
  horario: ['Horário'],
  fila: ['Fila'],
  obrigado: ['Obrigado'],
  'nao-entendi': ['Não entendi', 'Entender', 'Repetir'],
}

export const BUTCHER_INTENTS = BUTCHER_VOCABULARY.map(({ label, title, text, category, examples }) => ({
  label,
  title,
  text,
  sector: category,
  examples,
  expertClasses: VLIBRASIL_CLASS_ALIASES[label] || [],
}))
