export const LIBRAS_COURSE_PLAYLIST_ID = 'PL8vXuI6zmpdjRWqlbPUY5ASgO-ovJd0sf'
export const LIBRAS_COURSE_URL = `https://www.youtube.com/playlist?list=${LIBRAS_COURSE_PLAYLIST_ID}`

const lessonVideoIds = [
  'vsjdG2RBUKk', '46xkXUw4rWU', 'u_wGdqTkbJw', 'szbkqtb5-qs', 'l2TER1t5GnY',
  '6UUe2unBMbI', 'blYSTVEniJM', 'gSbexTmJg0I', 'inC67b5Yn-Y', '5EbGQaHzUco',
  'zZ4l3ko-kSU', 'Q0LX_n9xuqU', '_R9B8r1Lr4g', '635h4rJ7LxM', 'GlEmcGVXUDI',
  '_0O9hOGFM30', 'N3xTBy9GfLA', 'KiDoq3LnnNg', 'ulomPUPH9ps', 'gJDJD7cHN9A',
  '6N5Kihld364', 'ury-EJnLQ8A', 'rRI5bNJeDEI', 'SIr-ys1a07c', 'IeJ7Lxg7a2c',
  'zcN_9zlT4qM', 'uMIVI2uR7bo', 'BLUN2VazS0U', 'unhJPjS76Bg', 'TBtNen6hcAM',
  'JIG0uVQiHYU', '2bvstMduxn8', 'w8UV0lULjdc', 'tRl-5PlNyro', 'mGNgIKRRcM4',
  'nmxozazvFr0', 'R1lFfFZUQ1U', '740AFgideAU', '5mIZ53Gyx7A', 'U84dZE9j_PE',
  'wNQrYnY9BdU', 'xGqP0V11goE', '7rnwqqEz1r4', 'LizRkEjzAdU', 'xFZEEIfQyOM',
  'zA9fFhKd4XY', '0h7Ad-AnbFg', 'cUDBspUPDvk', 'TI-kzUy2h9M', '3C-Nj3Zt-QQ',
  '5JgylRectrI', 'KjvBa9u7iWs', '8G4YFEzcTm0', 'ce5CJiJJJpQ', 'fWYp632vRTY',
  'qXJscvBCnFU', 'szrvJXAzO0U', 'xB6wZBzbz1I', 'ubUJ0BFX9lc', 'hx9xoY1TURM',
  'Dz83YaICFBk', '69oMHY1li8E', 'txCqnBeP-oY', '1-l4J5hpvD8', 'LoR1kwAEbdc',
  'HFCY2wjRjhA', 'nBlBjW7qqHU', 'P_oDWDwVeaQ', 'GCo-AO8aHhM', 'V26CwW55kHg',
  'pX2QSWzYD4s',
]

const lessons = [
  ['Apresentação', 'base'],
  ['O que é Libras?', 'base'],
  ['Parâmetros da Libras', 'base'],
  ['Quem é o surdo?', 'cultura'],
  ['Quem é o TILS?', 'cultura'],
  ['Exercícios: parâmetros', 'base'],
  ['Exercícios: Libras e surdos', 'cultura'],
  ['Exercícios: TILS', 'cultura'],
  ['Alfabeto manual', 'alfabeto'],
  ['Exercícios: alfabeto manual', 'alfabeto'],
  ['Números', 'numeros'],
  ['Exercícios: números', 'numeros'],
  ['Apresentação pessoal', 'cumprimentos'],
  ['Exercícios: apresentação pessoal', 'cumprimentos'],
  ['Sinais de cumprimentos', 'cumprimentos'],
  ['Exercícios: cumprimentos', 'cumprimentos'],
  ['Diálogos em contexto', 'cumprimentos'],
  ['Exercícios: diálogos', 'cumprimentos'],
  ['Pronomes pessoais', 'gramatica'],
  ['Exercícios: pronomes pessoais', 'gramatica'],
  ['Pronomes interrogativos', 'gramatica'],
  ['Exercícios: pronomes interrogativos', 'gramatica'],
  ['Dias da semana e tempo — parte 1', 'tempo'],
  ['Dias da semana e tempo — parte 2', 'tempo'],
  ['Exercícios: dias da semana e tempo', 'tempo'],
  ['Sinais de meses', 'tempo'],
  ['Exercícios: meses', 'tempo'],
  ['Sinais de família', 'relacoes'],
  ['Exercícios: família', 'relacoes'],
  ['Sinais de cores', 'descricao'],
  ['Exercícios: cores', 'descricao'],
  ['Sinais de natureza', 'ambiente'],
  ['Exercícios: natureza', 'ambiente'],
  ['Sinais de animais', 'animais'],
  ['Exercícios: animais', 'animais'],
  ['Sinais de materiais escolares', 'objetos'],
  ['Exercícios: materiais escolares', 'objetos'],
  ['Sinais de esportes e brincadeiras — parte 1', 'lazer'],
  ['Sinais de esportes e brincadeiras — parte 2', 'lazer'],
  ['Exercícios: esportes e brincadeiras', 'lazer'],
  ['Sinais de profissões — parte 1', 'profissoes'],
  ['Sinais de profissões — parte 2', 'profissoes'],
  ['Exercícios: profissões', 'profissoes'],
  ['Sinais de alimentos — parte 1', 'alimentos'],
  ['Sinais de alimentos — parte 2', 'alimentos'],
  ['Exercícios: alimentos', 'alimentos'],
  ['Sinais de bebidas', 'bebidas'],
  ['Exercícios: bebidas', 'bebidas'],
  ['Sinais de meios de transportes — parte 1', 'transportes'],
  ['Sinais de meios de transportes — parte 2', 'transportes'],
  ['Exercícios: meios de transportes — parte 1', 'transportes'],
  ['Exercícios: meios de transportes — parte 2', 'transportes'],
  ['Sinais de locais públicos', 'locais'],
  ['Exercícios: locais públicos', 'locais'],
  ['Sinais de verbos', 'verbos'],
  ['Exercícios: verbos', 'verbos'],
  ['Verbos com negação', 'verbos'],
  ['Exercícios: verbos com negação', 'verbos'],
  ['Verbos direcionais', 'verbos'],
  ['Exercícios: verbos direcionais', 'verbos'],
  ['Adjetivos — parte 1', 'adjetivos'],
  ['Adjetivos — parte 2', 'adjetivos'],
  ['Exercícios: adjetivos', 'adjetivos'],
  ['Sentimentos — parte 1', 'sentimentos'],
  ['Sentimentos — parte 2', 'sentimentos'],
  ['Exercícios: sentimentos', 'sentimentos'],
  ['Introdução aos classificadores — parte 1', 'classificadores'],
  ['Introdução aos classificadores — parte 2', 'classificadores'],
  ['Exercícios: classificadores — parte 1', 'classificadores'],
  ['Exercícios: classificadores — parte 2', 'classificadores'],
  ['LIVE: encerramento do curso', 'encerramento'],
]

export const LIBRAS_COURSE_LESSONS = lessons.map(([title, topic], index) => ({
  number: index + 1,
  title,
  topic,
  videoId: lessonVideoIds[index],
  url: `https://www.youtube.com/watch?v=${lessonVideoIds[index]}&list=${LIBRAS_COURSE_PLAYLIST_ID}&index=${index + 1}`,
}))

export const LIBRAS_COURSE_PRIORITY = [
  11, 12, 15, 16, 17, 18,
  44, 45, 46, 47, 48,
  53, 54, 55, 56, 57, 58, 59, 60,
  61, 62, 63,
]

export const LIBRAS_COURSE_REVIEW = {
  source: 'Curso de Libras: Prática e Inclusão | Kultivi',
  playlistUrl: LIBRAS_COURSE_URL,
  totalLessons: LIBRAS_COURSE_LESSONS.length,
  reviewed: [
    {
      lesson: 11,
      videoId: 'zZ4l3ko-kSU',
      status: 'parcial',
      observedUntilSeconds: 257,
      notes: [
        'Apresenta números cardinais de 0 a 10 e exemplos de números maiores.',
        'A professora explica que a execução pode ser invertida quando a pessoa usa a outra mão.',
        'Os sinais devem ser cadastrados a partir de exemplos visuais, não apenas pelo título da aula.',
      ],
    },
    {
      lesson: 15,
      videoId: 'GlEmcGVXUDI',
      status: 'parcial',
      observedUntilSeconds: 153,
      notes: [
        'Apresenta bom dia, boa tarde e boa noite, incluindo variações.',
        'A execução é demonstrada de frente e com orientação para visualizar o movimento.',
      ],
    },
    {
      lesson: 44,
      videoId: 'LizRkEjzAdU',
      status: 'parcial',
      observedUntilSeconds: 401,
      notes: [
        'Introduz comer, fome, alimentos/comida, prato, copo, garfo, faca, colher e guardanapo.',
        'A aula destaca que configuração e orientação da mão fazem parte do sinal.',
      ],
    },
  ],
}
